name: rest_client
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/peiffer-innovations/rest_client

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  meta: ^1.1.8
  intl: ^0.16.1
  logging: ^0.11.4
  uuid: ^2.0.4

dev_dependencies:
  test: any
  test_coverage: any

