name: Dart Pull Request Checker

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub upgrade
    - name: Dart Analyzer
      run: dartanalyzer lib
    - name: Run tests
      run: pub run test
    - name: Run test coverage
      run: pub run test_coverage

